# Generated by Django 5.1.7 on 2025-03-28 12:21

import product.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productline_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productline',
            name='order',
            field=product.fields.OrderField(blank=True, null=True),
        ),
    ]
